services:
  - type: web_service
    name: api-node-royal-harvest
    env: node
    plan: starter
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    root: .
    envVars:
      - key: GMAIL_USER
        value: sandamharish2003@gmail.com
      - key: GMAIL_PASS
        value: ltsjzaxzvhzxirru
      - key: RECEIVER_EMAIL
        value: sandamharish2003@gmail.com
